apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpZeApPREE0TURKYUZ3MDBNekF4TWpZeE9EQTRNREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDeFhUdWVHT01ZLzZBL2lIQTZLc0VlcHN5QmxMV1hLNmJYbjRCMW12SjBWQ212ZzBwZwpJV3MrdXRCMVdnMHA5MkFDYkNENVBuZUZ1U0NHZlZXTUdzeWpQY2orTG5saVM1ZWFsVFNtZGFCaFdhT3RudTdnCjdVSlp0VDdsaE93NW1qTURLczN4QjE5OU9lTEhiczNWa0NodXV4U00zeENjdnI0OFRzUFhrS3FZSGcxZ1RvWVQKcFA3bWFkb3ZaM0loc1dDQmIycDZITEg1VmdTNlo5SXgraUl5N01pYmZvMm9mNlBvV210alZUcitJZkVaYTB2dAp0ZnUxZkxjb0EydnA5Y3lpcTV4QXBqSS9pWS9CamptR3pQSElOK0o0MkJvSFA1cXV0NHRvWlhMQWZjMEFPeElBCnZvUFdCcm9hS0hlM3djTXl0Vzd4dmhHMXNhMm5ybll0SXQ4dkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFneC9xcnc1UExpT21WaW5FVAoweFI4SjRZSHpEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFlanM5T1JZY0pZK1doVW5zNUd6NkNnbVNqT0Q5ClZtQ0kzUlhqc05NOSsxY01HemoxTkNWSi9UaVEwekZycHhkNHE0QVc3UGRqY2o0K2MyL2JDOHk0Z3YxZnpLOEEKZjYwa240V0o3ZWlGNVZzclY1WTBudnFlYWNYZ1JrTFBrWWlkSjlia2JWb3Nzcm9rcW5TdFg2ZlNIbEZ1Sm0vNQpRMFMzSW5BbjMydytaZW9tM2FjMUNSVXBXNVdvekNPOGhLYWxCdDdXVFVycFI3UVEwaFlRWktmbFVlNWdhUXZYCmlHbUV2RXQ5cUxZSjRid1BkdTNwSFlsS1pYcElEQjRFaVRFbnBwSWdCblRoRUpvemdmcUt0dityd3drQmlMOHUKUnZWMU03OTZGQ2ptSkNTMm8xQWIzM290cTB5SnlmeTBDUWY4enVQZEZOL21YUlFUOXc5KzAzMEMxZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://b7828453-d477-4a62-8313-56e660cd30bc.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_d7ff9bb9ab85d7237e1f908eec141cda9dfca5f596fbbaef1b80e8736405edf5
